export interface Startup {
  id: string;
  name: string;
  description: string;
  category: string;
  stage: string;
  status: 'published' | 'draft' | 'archived';
  raised: number;
  target: number;
  valuation: number;
  equitySold: number;
  mrr: number;
  tvl: number;
  runway: number;
  teamSize: number;
  score: number;
  closesIn: string;
  platform: string;
  featured: boolean;
  trending: boolean;
  abstract: string;
  logoUrl: string;
  docsUrl: string;
  twitterUrl: string;
  discordUrl: string;
  latencyBenchmark?: string;
  usersCount?: string;
  closedTime?: string;
}

export interface ResearchItem {
  id: string;
  title: string;
  category: string;
  readTime: string;
}

export const INITIAL_RESEARCH_ITEMS: ResearchItem[] = [
  {
    id: 'R1',
    title: 'The State of Liquid Staking Derivatives on Solana',
    category: 'RESEARCH DEPT',
    readTime: '4 MIN READ',
  },
  {
    id: 'R2',
    title: 'Understanding Parallelized Execution Engines',
    category: 'TECH ANALYST',
    readTime: '12 MIN READ',
  },
  {
    id: 'R3',
    title: 'MEV Redistribution Mechanisms and SVM Blockspace Pricing',
    category: 'INFRA STRUCTURE',
    readTime: '8 MIN READ',
  }
];

export const INITIAL_STARTUPS: Startup[] = [
  {
    id: 'SOL-8842-X',
    name: 'Aether Protocol',
    description: 'Building the decentralized liquidity layer for high-frequency institutional trading on Solana. Sub-millisecond execution with provable audit trails.',
    category: 'INFRASTRUCTURE / DEFI',
    stage: 'Strategic Round',
    status: 'published',
    raised: 3690000,
    target: 4500000,
    valuation: 45000000,
    equitySold: 10.0,
    mrr: 85000,
    tvl: 340000000,
    runway: 18,
    teamSize: 18,
    score: 94,
    closesIn: '03D : 18H : 30M',
    platform: 'INTERNAL',
    featured: true,
    trending: true,
    latencyBenchmark: '0.12ms',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2uxQBMytgBsy-vHLefyQdko6YvfI2TFTWpP6mcBTJ_AhBsY-2DYH-XxKBVjp3yb3Oqh7vsPCc9Mcdjm1WJPt1O6JePUyJtKrFLZ5n-5RzG_1-ca5bKyvqNYrDz1Ous0eTDDDmA4HmeC2aMRp_fGz3X6m3ICKAgCQkCrm5fzKeUdASMcJMbvP05-lRPVpYf6XLOlSYZy6D8UfJOEAzc5GKgUUkgIA6PsypmWnxZ4lCKQRcyWSWbxPTBrJemNIWYA8jV-S6mgzyZL2h',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: "Aether Protocol addresses the core challenge of institutional liquidity on-chain. By using standard-setting hardware acceleration and Solana's localized fee markets, Aether processes institutional volumes with guaranteed execution slots and transparent execution verification.",
  },
  {
    id: 'SOL-1200-A',
    name: 'Lumina Protocol',
    description: 'Decentralized Compute & Orchestration for Solana L2s and SVM environments.',
    category: 'INFRASTRUCTURE',
    stage: 'Strategic Round',
    status: 'published',
    raised: 4200000,
    target: 5000000,
    valuation: 32000000,
    equitySold: 13.1,
    mrr: 42500,
    tvl: 128400000,
    runway: 24,
    teamSize: 14,
    score: 82,
    closesIn: '04D : 12H : 08M',
    platform: 'INTERNAL',
    featured: false,
    trending: true,
    latencyBenchmark: '0.45ms',
    usersCount: '8.2K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCfr-AmrXhDXlNTbWcNzWq8-fKAdrYJd6FXHIJPH1ora_mYy00WIhSy9rBJra_LS4Xbv4Eze2EPRy_PLW_gCyfHYO_sNZOpiFFkj45mqqZW9GDP9SZ4JGKBkw8mrCzoacL3-87Fe1zDwOXRqdfSnbrNP-7XMm_PVf-0f64CxiDucyfV1lGTtnJ3vMQ0YNngBdhLjDAgq9fawf4nlgB4Ue1aDqHoN5VvgdbQiXaB4waTwrGtdjPljf4xyoAqL5edp_nhMbGkv4D9jXM',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Lumina Protocol is a high-performance compute orchestration layer specifically designed for Solana-based Layer 2 rollups and SVM environments. By leveraging a novel proof-of-compute mechanism, Lumina ensures deterministic execution and verification of off-chain transactions while maintaining atomic composability with the Solana L1.',
  },
  {
    id: 'SOL-4401-K',
    name: 'Solayer',
    description: 'First-class restaking network natively integrated with Solana block production, enabling decentralized application security.',
    category: 'RESTAKING',
    stage: 'Series A',
    status: 'published',
    raised: 14250000,
    target: 15000000,
    valuation: 80000000,
    equitySold: 17.8,
    mrr: 120000,
    tvl: 240000000,
    runway: 36,
    teamSize: 22,
    score: 94,
    closesIn: '02H : 45M',
    platform: 'INTERNAL',
    featured: false,
    trending: true,
    usersCount: '12.4K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2uxQBMytgBsy-vHLefyQdko6YvfI2TFTWpP6mcBTJ_AhBsY-2DYH-XxKBVjp3yb3Oqh7vsPCc9Mcdjm1WJPt1O6JePUyJtKrFLZ5n-5RzG_1-ca5bKyvqNYrDz1Ous0eTDDDmA4HmeC2aMRp_fGz3X6m3ICKAgCQkCrm5fzKeUdASMcJMbvP05-lRPVpYf6XLOlSYZy6D8UfJOEAzc5GKgUUkgIA6PsypmWnxZ4lCKQRcyWSWbxPTBrJemNIWYA8jV-S6mgzyZL2h',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: "Solayer leverages Solana's underlying consensus and transaction pipeline to secure exogenous systems (AVSs). Users deposit SOL or LSTs to earn native yield while supporting security infrastructure across modular ecosystem integrations.",
  },
  {
    id: 'SOL-5511-M',
    name: 'Arch',
    description: 'Bitcoin programmability layer and scaling solution leveraging Solana execution engines.',
    category: 'INFRASTRUCTURE',
    stage: 'Seed Round',
    status: 'published',
    raised: 2100000,
    target: 5000000,
    valuation: 45000000,
    equitySold: 4.6,
    mrr: 45000,
    tvl: 12000000,
    runway: 18,
    teamSize: 8,
    score: 81,
    closesIn: '1D : 12H',
    platform: 'FJORD',
    featured: false,
    trending: false,
    usersCount: '4.2K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCfr-AmrXhDXlNTbWcNzWq8-fKAdrYJd6FXHIJPH1ora_mYy00WIhSy9rBJra_LS4Xbv4Eze2EPRy_PLW_gCyfHYO_sNZOpiFFkj45mqqZW9GDP9SZ4JGKBkw8mrCzoacL3-87Fe1zDwOXRqdfSnbrNP-7XMm_PVf-0f64CxiDucyfV1lGTtnJ3vMQ0YNngBdhLjDAgq9fawf4nlgB4Ue1aDqHoN5VvgdbQiXaB4waTwrGtdjPljf4xyoAqL5edp_nhMbGkv4D9jXM',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: "Arch is an execution layer built directly on Bitcoin utilizing zero-knowledge proofs. It unlocks decentralized finance and trustless token swaps without modifying Bitcoin's base protocol layers.",
  },
  {
    id: 'SOL-9011-H',
    name: 'Drift L2',
    description: 'The premier decentralized futures and spot trading platform utilizing an L2 scaling SVM design.',
    category: 'DEFI',
    stage: 'Series A',
    status: 'published',
    raised: 8900000,
    target: 10000000,
    valuation: 250000000,
    equitySold: 3.56,
    mrr: 2100000,
    tvl: 410000000,
    runway: 24,
    teamSize: 31,
    score: 98,
    closesIn: '4D : 06H',
    platform: 'JUP LFG',
    featured: false,
    trending: true,
    usersCount: '88K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkiJ7JO4AE7LsS6J5IhUg_VTL_g6K0MsB5L181uBNhK5cGjfVS4hF_WcOe2a9OOnORVhU7qW2p2E_cFqtB31b0b7DCUjRsWVa-ypHyK_hIQ1AI_JQVScaDEeDSGNHc9ndL9CPQCo8_cofGkanSKTm7XMkXyLkRQlULqflI_UF3V0VQtZtUz2r5quWqC6HW2XfTRPQc0apJioH4UG4AS5Cb1R8_QtS7u3SuVO1kupmkHeJqT_IATt_DaOvfh-tiJNaZEGDcGxfpMFR',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Drift L2 leverages parallel execution to run a fully on-chain virtual automated market maker (vAMM) and decentralized orderbook. It brings professional market making standards to Solana without compromising security.',
  },
  {
    id: 'SOL-3021-Z',
    name: 'Zeus Network',
    description: 'Cross-chain communication network unlocking liquidity flow between Bitcoin and Solana ecosystems.',
    category: 'INTEROPERABILITY',
    stage: 'Seed Plus',
    status: 'published',
    raised: 4500000,
    target: 12000000,
    valuation: 120000000,
    equitySold: 3.75,
    mrr: 0,
    tvl: 0,
    runway: 18,
    teamSize: 11,
    score: 72,
    closesIn: '12H : 10M',
    platform: 'FJORD',
    featured: false,
    trending: false,
    usersCount: '15.5K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2uxQBMytgBsy-vHLefyQdko6YvfI2TFTWpP6mcBTJ_AhBsY-2DYH-XxKBVjp3yb3Oqh7vsPCc9Mcdjm1WJPt1O6JePUyJtKrFLZ5n-5RzG_1-ca5bKyvqNYrDz1Ous0eTDDDmA4HmeC2aMRp_fGz3X6m3ICKAgCQkCrm5fzKeUdASMcJMbvP05-lRPVpYf6XLOlSYZy6D8UfJOEAzc5GKgUUkgIA6PsypmWnxZ4lCKQRcyWSWbxPTBrJemNIWYA8jV-S6mgzyZL2h',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Zeus Network acts as a programmable communication layer connecting decentralized consensus networks. By facilitating trustless state tracking on Bitcoin and Solana, users can natively trade asset pairs with minimal friction.',
  },
  {
    id: 'SOL-7744-Y',
    name: 'Sonic',
    description: 'Hyper-performance gaming ecosystem and SVM sovereign layer for decentralized gaming applications.',
    category: 'AI / ML',
    stage: 'Series A',
    status: 'published',
    raised: 6200000,
    target: 8000000,
    valuation: 65000000,
    equitySold: 9.5,
    mrr: 12000,
    tvl: 8500000,
    runway: 18,
    teamSize: 15,
    score: 89,
    closesIn: '2D : 04H',
    platform: 'JUP LFG',
    featured: false,
    trending: true,
    usersCount: '120K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCfr-AmrXhDXlNTbWcNzWq8-fKAdrYJd6FXHIJPH1ora_mYy00WIhSy9rBJra_LS4Xbv4Eze2EPRy_PLW_gCyfHYO_sNZOpiFFkj45mqqZW9GDP9SZ4JGKBkw8mrCzoacL3-87Fe1zDwOXRqdfSnbrNP-7XMm_PVf-0f64CxiDucyfV1lGTtnJ3vMQ0YNngBdhLjDAgq9fawf4nlgB4Ue1aDqHoN5VvgdbQiXaB4waTwrGtdjPljf4xyoAqL5edp_nhMbGkv4D9jXM',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Sonic enables game developers to build custom sovereign app-chains with sub-millisecond execution times. Its native gas monetization engine allows game teams to capture gas fee value, redirecting resources back into their active player economies.',
  },
  {
    id: 'SOL-2291-E',
    name: 'Elixir',
    description: 'Decentralized orderbook liquidity network powering high-performance exchange infrastructure.',
    category: 'INFRASTRUCTURE',
    stage: 'Series A',
    status: 'published',
    raised: 18500000,
    target: 20000000,
    valuation: 300000000,
    equitySold: 6.1,
    mrr: 0,
    tvl: 800000000,
    runway: 30,
    teamSize: 19,
    score: 91,
    closesIn: '5D : 18H',
    platform: 'FJORD',
    featured: false,
    trending: false,
    usersCount: '45K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkiJ7JO4AE7LsS6J5IhUg_VTL_g6K0MsB5L181uBNhK5cGjfVS4hF_WcOe2a9OOnORVhU7qW2p2E_cFqtB31b0b7DCUjRsWVa-ypHyK_hIQ1AI_JQVScaDEeDSGNHc9ndL9CPQCo8_cofGkanSKTm7XMkXyLkRQlULqflI_UF3V0VQtZtUz2r5quWqC6HW2XfTRPQc0apJioH4UG4AS5Cb1R8_QtS7u3SuVO1kupmkHeJqT_IATt_DaOvfh-tiJNaZEGDcGxfpMFR',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Elixir network acts as an algorithmic market maker feeding direct liquidity into Orderbooks on decentralized exchanges. Its cryptographically secure orchestrator rewards capital pools for systematic bidding.',
  },
  {
    id: 'SOL-8822-M',
    name: 'Aura Network',
    description: 'Institutional-grade cryptographic consensus network supporting localized high-frequency SVM engines.',
    category: 'INFRASTRUCTURE',
    stage: 'Seed Round',
    status: 'published',
    raised: 2100000,
    target: 3000000,
    valuation: 15000000,
    equitySold: 14.0,
    mrr: 5000,
    tvl: 500000,
    runway: 12,
    teamSize: 6,
    score: 88,
    closesIn: '04D : 12H : 08M',
    platform: 'INTERNAL',
    featured: false,
    trending: false,
    usersCount: '1.5K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2uxQBMytgBsy-vHLefyQdko6YvfI2TFTWpP6mcBTJ_AhBsY-2DYH-XxKBVjp3yb3Oqh7vsPCc9Mcdjm1WJPt1O6JePUyJtKrFLZ5n-5RzG_1-ca5bKyvqNYrDz1Ous0eTDDDmA4HmeC2aMRp_fGz3X6m3ICKAgCQkCrm5fzKeUdASMcJMbvP05-lRPVpYf6XLOlSYZy6D8UfJOEAzc5GKgUUkgIA6PsypmWnxZ4lCKQRcyWSWbxPTBrJemNIWYA8jV-S6mgzyZL2h',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Aura Network is optimized for fast, hardware-backed validators. It enforces strict zero-knowledge proofs on state updates, allowing SVM layers to commit transitions directly to the mainnet with extreme finality guarantees.',
  },
  {
    id: 'SOL-1102-S',
    name: 'Neural Sol',
    description: 'Decentralized hardware virtualization layer and decentralized marketplace for model inference execution.',
    category: 'AI / ML',
    stage: 'Strategic Round',
    status: 'published',
    raised: 850000,
    target: 1200000,
    valuation: 10000000,
    equitySold: 8.5,
    mrr: 15000,
    tvl: 0,
    runway: 15,
    teamSize: 5,
    score: 91,
    closesIn: '01D : 22H : 45M',
    platform: 'INTERNAL',
    featured: false,
    trending: true,
    usersCount: '3.1K',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkiJ7JO4AE7LsS6J5IhUg_VTL_g6K0MsB5L181uBNhK5cGjfVS4hF_WcOe2a9OOnORVhU7qW2p2E_cFqtB31b0b7DCUjRsWVa-ypHyK_hIQ1AI_JQVScaDEeDSGNHc9ndL9CPQCo8_cofGkanSKTm7XMkXyLkRQlULqflI_UF3V0VQtZtUz2r5quWqC6HW2XfTRPQc0apJioH4UG4AS5Cb1R8_QtS7u3SuVO1kupmkHeJqT_IATt_DaOvfh-tiJNaZEGDcGxfpMFR',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Neural Sol coordinates underutilized high-performance compute arrays globally. By providing standardized containers, machine learning teams run complex agent behaviors securely and cost-effectively.',
  },
  {
    id: 'SOL-5592-W',
    name: 'Vanguard Wallets',
    description: 'Multi-party computation smart custody suite for high-net-worth funds and trading desks.',
    category: 'DEFI',
    stage: 'Series A',
    status: 'published',
    raised: 4200000,
    target: 5000000,
    valuation: 40000000,
    equitySold: 10.5,
    mrr: 35000,
    tvl: 2500000000,
    runway: 24,
    teamSize: 12,
    score: 76,
    closesIn: '12D : 05H : 12M',
    platform: 'FJORD',
    featured: false,
    trending: false,
    usersCount: '250',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCfr-AmrXhDXlNTbWcNzWq8-fKAdrYJd6FXHIJPH1ora_mYy00WIhSy9rBJra_LS4Xbv4Eze2EPRy_PLW_gCyfHYO_sNZOpiFFkj45mqqZW9GDP9SZ4JGKBkw8mrCzoacL3-87Fe1zDwOXRqdfSnbrNP-7XMm_PVf-0f64CxiDucyfV1lGTtnJ3vMQ0YNngBdhLjDAgq9fawf4nlgB4Ue1aDqHoN5VvgdbQiXaB4waTwrGtdjPljf4xyoAqL5edp_nhMbGkv4D9jXM',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: "Vanguard Wallets delivers customized cryptographic signature engines to financial organizations. Its zero-knowledge architecture enforces strict risk bounds while giving portfolio teams instant liquidity access.",
  },
  {
    id: 'SOL-2211-N',
    name: 'Eclipse VM',
    description: 'The modular SVM Rollup using Ethereum for security and Celestia for data availability.',
    category: 'L2 SOLUTIONS',
    stage: 'Seed Plus',
    status: 'draft',
    raised: 1500000,
    target: 5000000,
    valuation: 22500000,
    equitySold: 6.6,
    mrr: 0,
    tvl: 50000000,
    runway: 18,
    teamSize: 8,
    score: 84,
    closesIn: '08D : 06H',
    platform: 'INTERNAL',
    featured: false,
    trending: false,
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCfr-AmrXhDXlNTbWcNzWq8-fKAdrYJd6FXHIJPH1ora_mYy00WIhSy9rBJra_LS4Xbv4Eze2EPRy_PLW_gCyfHYO_sNZOpiFFkj45mqqZW9GDP9SZ4JGKBkw8mrCzoacL3-87Fe1zDwOXRqdfSnbrNP-7XMm_PVf-0f64CxiDucyfV1lGTtnJ3vMQ0YNngBdhLjDAgq9fawf4nlgB4Ue1aDqHoN5VvgdbQiXaB4waTwrGtdjPljf4xyoAqL5edp_nhMbGkv4D9jXM',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: "Eclipse VM is building Ethereum's fastest layer 2, utilizing the Solana Virtual Machine (SVM) execution engine. This architecture combines Ethereum's robust consensus with Celestia's efficient storage and Solana's legendary speed.",
  },
  {
    id: 'SOL-1309-P',
    name: 'Synapse Labs',
    description: 'Machine learning data pipeline optimization and zero-knowledge model execution.',
    category: 'AI & DATA',
    stage: 'Pre-Seed',
    status: 'archived',
    raised: 600000,
    target: 1000000,
    valuation: 12000000,
    equitySold: 5.0,
    mrr: 2000,
    tvl: 0,
    runway: 12,
    teamSize: 4,
    score: 68,
    closesIn: 'CLOSED',
    platform: 'FJORD',
    featured: false,
    trending: false,
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkiJ7JO4AE7LsS6J5IhUg_VTL_g6K0MsB5L181uBNhK5cGjfVS4hF_WcOe2a9OOnORVhU7qW2p2E_cFqtB31b0b7DCUjRsWVa-ypHyK_hIQ1AI_JQVScaDEeDSGNHc9ndL9CPQCo8_cofGkanSKTm7XMkXyLkRQlULqflI_UF3V0VQtZtUz2r5quWqC6HW2XfTRPQc0apJioH4UG4AS5Cb1R8_QtS7u3SuVO1kupmkHeJqT_IATt_DaOvfh-tiJNaZEGDcGxfpMFR',
    docsUrl: '#',
    twitterUrl: '#',
    discordUrl: '#',
    abstract: 'Synapse Labs automates decentralized data validation for deep neural network training. By applying localized zk-proof checks, it avoids heavy cloud-compute overheads while ensuring source authenticity.',
  }
];
